// Code generated by "stringer -type=LogAction -linecomment"; DO NOT EDIT.

package helpers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogActionView-1]
	_ = x[LogActionAdd-2]
	_ = x[LogActionUpdate-3]
	_ = x[LogActionDelete-4]
}

const _LogAction_name = "VIEWADDUPDATEDELETE"

var _LogAction_index = [...]uint8{0, 4, 7, 13, 19}

func (i LogAction) String() string {
	i -= 1
	if i < 0 || i >= LogAction(len(_LogAction_index)-1) {
		return "LogAction(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogAction_name[_LogAction_index[i]:_LogAction_index[i+1]]
}
