codecov:
  require_ci_to_pass: false

ignore:
  - "api/v1alpha1/zz_generated.deepcopy.go"
  - "api/v1beta1/zz_generated.deepcopy.go"
  - "api/v1beta2/zz_generated.deepcopy.go"
  - "gitops/integrationteststatus_enumer.go"
  - "status/mock_reporter.go"
  - "status/mock_status.go"
  - "e2e-tests/**"
  - "vendor/**"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  require_changes: true
