{
 "title": "Integration Service Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Integration service CPU utilization percentage",
   "type": "timeseries",
   "description": "The percentage % of CPU utilization consumed by the integration service.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * rate(container_cpu_usage_seconds_total{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-.*\", container=\"manager\"}[5m]) / on (container, pod) kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"integration-service\",pod=~\"integration-service-controller-manager-.*\", container=\"manager\"}",
     "legendFormat": "% of integration service manager CPU utilization {{pod}}"
    }
   ]
  },
  {
   "title": "Integration service Memory utilization percentage",
   "type": "timeseries",
   "description": "The percentage % of memory utilization consumed by the integration service.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * container_memory_working_set_bytes{namespace=\"integration-service\",pod=~\"integration-service-controller-manager-.*\", container=\"manager\"}  / on (pod) kube_pod_container_resource_limits{resource=\"memory\",namespace=\"integration-service\",pod=~\"integration-service-controller-manager-.*\", container=\"manager\"}",
     "legendFormat": "% of integration service manager memory utilization {{pod}}"
    }
   ]
  },
  {
   "title": "The reconcilation errors per controller",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_errors_total{namespace=\"integration-service\", controller=\"snapshot\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "controller_runtime_reconcile_errors_total{namespace=\"integration-service\", controller=\"pipelinerun\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "controller_runtime_reconcile_errors_total{namespace=\"integration-service\", controller=\"component\"}",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "controller_runtime_reconcile_errors_total{namespace=\"integration-service\", controller=\"integrationtestscenario\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}