{
 "title": "Integration Service",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Integration Service Availability ",
   "type": "graph",
   "description": "Measure the uptime for Integration Service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(redhat_appstudio_integrationservice_global_github_app_available[1h]) * 100\n",
     "legendFormat": "99% uptime required"
    }
   ]
  },
  {
   "title": "[Violations] Integration Service Availability",
   "type": "timeseries",
   "description": "Uptime of 99%",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(redhat_appstudio_integrationservice_global_github_app_available[1h]) * 100\n",
     "legendFormat": "% uptime"
    }
   ]
  },
  {
   "title": "SLOs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "#1 Latency - Percentile Service Response (in-progress change)",
   "type": "graph",
   "description": "Measure the response time it takes to successfully mark/update a Integration Service CR in the Integration controller as in progress from the build PipelineRun is finished",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(integration_svc_response_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "percentile90"
    }
   ]
  },
  {
   "title": "[Violations] #1 Latency - Percentile Service Response (in-progress change)",
   "type": "timeseries",
   "description": "90% of requests must take less than 30sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(integration_svc_response_seconds_bucket{le=\"30\"}[$__rate_interval])) by (job)\n/\nsum(rate(integration_svc_response_seconds_count[$__rate_interval]) > 0) by (job)\n*100",
     "legendFormat": "% of requests within required latency time"
    }
   ]
  },
  {
   "title": "#2A Time to Start PipelineRun",
   "type": "graph",
   "description": "Measure the time between ApplicationSnapshot creation to pipelineRun creation in a static env. \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(integration_svc_snapshot_created_to_pipelinerun_started_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "percentile90"
    }
   ]
  },
  {
   "title": "[Violations] #2A Time to Start PipelineRun",
   "type": "timeseries",
   "description": "90% of requests must take less than 5sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(integration_svc_snapshot_created_to_pipelinerun_with_static_env_started_seconds_bucket{le=\"5\"}[$__rate_interval])) by (job)\n/\nsum(rate(integration_svc_snapshot_created_to_pipelinerun_with_static_env_started_seconds_count[$__rate_interval]) > 0) by (job)\n*100",
     "legendFormat": "% of requests within required latency time"
    }
   ]
  },
  {
   "title": "#5 Latency of Release Creation",
   "type": "graph",
   "description": "Measure release creation latency from end of testing to release created \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(integration_svc_release_latency_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "percentile90"
    }
   ]
  },
  {
   "title": "[Violations] #5 Latency of Release Creation",
   "type": "timeseries",
   "description": "90% of requests must take less than 10 sec. Measure release creation latency from end of testing to release created ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(integration_svc_release_latency_seconds_bucket{le=\"10\"}[$__rate_interval])) by (job) / sum(rate(integration_svc_release_latency_seconds_count[$__rate_interval])) by (job)*100",
     "legendFormat": "% of requests within required latency time"
    }
   ]
  },
  {
   "title": "SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Integration Pipelineruns",
   "type": "timeseries",
   "description": "Total number of integration PipelineRun created",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "integration_svc_integration_pipelinerun_total",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Snapshot Attempts Total",
   "type": "graph",
   "description": "Total number of snapshots processed by the operator",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "integration_svc_snapshot_attempt_total",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Integration Service Response Seconds",
   "type": "heatmap",
   "description": "Integration service response time from the moment the buildPipelineRun is completed till the snapshot is marked as in progress status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": " sum(increase(integration_svc_response_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Snapshot Created to PipelineRun",
   "type": "heatmap",
   "description": "Time duration from the moment the snapshot resource was created till a integration pipelineRun is started",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(integration_svc_snapshot_created_to_pipelinerun_with_static_env_started_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Snapshot Attempt Duration Seconds",
   "type": "heatmap",
   "description": "Snapshot durations from the moment the Snapshot was created till the Snapshot is marked as finished",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(integration_svc_snapshot_attempt_duration_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=\"snapshot\", namespace=\"integration-service\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "workqueue_depth{name=\"integrationtestscenario\", namespace=\"integration-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Duration Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(workqueue_queue_duration_seconds_bucket{name=\"snapshot\", namespace=\"integration-service\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(workqueue_queue_duration_seconds_bucket{name=\"integrationtestscenario\", namespace=\"integration-service\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Latency of Release Creation in Seconds",
   "type": "heatmap",
   "description": "Measure release creation latency from end of testing to release created ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(increase(integration_svc_release_latency_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}