kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: integration-service

configMapGenerator:
  - name: grafana-dashboard-integration-service
    files:
      - dashboards/integration-service-dashboard.json
  - name: grafana-dashboard-integration-service-health
    files:
      - dashboards/integration-service-health.json
resources:
  - dashboard.yaml