namePrefix: integration-service-

resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml

# Integration service
- integrationtestscenario_editor_role.yaml
- integrationtestscenario_viewer_role.yaml
- integrationtestscenario_role_binding.yaml

# Application service
- application_viewer_role.yaml
- application_role_binding.yaml
- component_editor_role.yaml
- component_viewer_role.yaml
- component_role_binding.yaml
# Release service
- release_editor_role.yaml
- release_viewer_role.yaml
- release_role_binding.yaml
- releaseplan_viewer_role.yaml
- releaseplan_role_binding.yaml
# Tekton
- tekton_editor_role.yaml
- tekton_role_binding.yaml
# GitOps
- snapshot_editor_role.yaml
- snapshot_role_binding.yaml
- snapshot_viewer_role.yaml
- snapshotenvironmentbinding_editor_role.yaml
- snapshotenvironmentbinding_role_binding.yaml
- environment_editor_role.yaml
- environment_role_binding.yaml
