# permissions for end users to edit snapshotenvironmentbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotenvironmentbinding-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshotenvironmentbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshotenvironmentbindings/status
  verbs:
  - get
