# permissions for end users to view integrationscenarios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrationscenario-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - integrationscenarios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - integrationscenarios/status
  verbs:
  - get
