# permissions for prometheus to view custom metrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-viewer-role
rules:
  - nonResourceURLs:
    - /metrics
    verbs: [get]
