# permissions for end users to view releaselinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaselink-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaselinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaselinks/status
  verbs:
  - get
