---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshot-garbage-collector
  namespace: system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-garbage-collector
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releases
  verbs:
  - get
  - list
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshots
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshot-garbage-collector
subjects:
- kind: ServiceAccount
  name: snapshot-garbage-collector
  namespace: system
roleRef:
  kind: ClusterRole
  name: snapshot-garbage-collector
  apiGroup: rbac.authorization.k8s.io
