apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kcp.dev/cluster: root:users:xr:vd:rh-sso-<account>:test-workspace
  labels:
    workspaces.kcp.dev/name: test-workspace
  name: clusterrolebinding-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole-integration
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
