apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot-garbage-collector
spec:
  schedule: "0 */6 * * *" # 4 times daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test-gc
              image: >-
                quay.io/konflux-ci/integration-service:latest
              command:
                - /snapshotgc
                - --zap-log-level=debug
                - --pr-snapshots-to-keep=70
                - --non-pr-snapshots-to-keep=600
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 1000m
                  memory: 500Mi
                limits:
                  cpu: 1000m
                  memory: 500Mi
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
          restartPolicy: Never
          serviceAccountName: snapshot-garbage-collector
