# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: integrationtestscenarios.appstudio.redhat.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1alpha1", "v1beta1", "v1beta2"]
      clientConfig:
        service:
          namespace: system
          name: webhook-service
          path: /convert
