apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kcp.dev/cluster: root:users:xr:vd:rh-sso-<account>:test-workspace
  labels:
    workspaces.kcp.dev/name: test-workspace
  name: clusterrole-integration
rules:
- apiGroups:
  - tenancy.kcp.dev
  resourceNames:
  - test-workspace
  resources:
  - workspaces
  verbs:
  - get
  - delete
- apiGroups:
  - tenancy.kcp.dev
  resourceNames:
  - test-workspace
  resources:
  - workspaces/content
  verbs:
  - admin
  - access
- apiGroups:
  - apis.kcp.dev
  resourceNames:
  - kubernetes
  resources:
  - apiexports
  verbs:
  - bind
