apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: integration-binding
spec:
  reference:
    workspace:
      path: ${kcp_workspace}
      exportName: integration-service
  permissionClaims:
    - resource: pipelineruns
      group: tekton.dev
      identityHash: pipeline-service
      state: Accepted
    - resource: applications
      group: appstudio.redhat.com
      identityHash: application-api
      state: Accepted
    - resource: components
      group: appstudio.redhat.com
      identityHash: application-api
      state: Accepted
    - resource: snapshots
      group: appstudio.redhat.com
      identityHash: application-api
      state: Accepted
    - resource: environments
      group: appstudio.redhat.com
      identityHash: application-api
      state: Accepted
    - resource: snapshotenvironmentbindings
      group: appstudio.redhat.com
      identityHash: application-api
      state: Accepted
    - resource: releases
      group: appstudio.redhat.com
      identityHash: release-service
      state: Accepted
    - resource: releaseplans
      group: appstudio.redhat.com
      identityHash: release-service
      state: Accepted
