# Adds namespace to all resources.
namespace: integration-service-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: integration-service-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
  - ../crd
  - ../manager
  - ../rbac

resources:
  - apiexport_integration.yaml
  - apiresourceschema_integration.yaml

patches:
# Needs to use default service account name right now
- patch: |-
    - op: replace
      path: /spec/template/spec/serviceAccountName
      value: default
  target:
    kind: Deployment
    name: controller-manager
