# Adds namespace to all resources.
# namespace: integration-service-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
# namePrefix: integration-service-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
  - ../manager
  - ../kcp-rbac

resources:
  - apiexport_integration.yaml
  - apiresourceschema_integration.yaml

patches:
# Add APIExport flag to the operator arguments list
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --api-export-name=integration-service
  target:
    kind: Deployment
    name: integration-service-controller-manager
