// Code generated by MockGen. DO NOT EDIT.
// Source: status/status.go
// Source: github.com/konflux-ci/integration-service/status (interfaces: StatusInterface)
//
// Generated by this command:
//
// mockgen -source=status/status.go -destination=status/mock_status.go -package=status
// Package status is a generated GoMock package.
package status

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/konflux-ci/application-api/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusInterface is a mock of StatusInterface interface.
type MockStatusInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStatusInterfaceMockRecorder
}

// MockStatusInterfaceMockRecorder is the mock recorder for MockStatusInterface.
type MockStatusInterfaceMockRecorder struct {
	mock *MockStatusInterface
}

// NewMockStatusInterface creates a new mock instance.
func NewMockStatusInterface(ctrl *gomock.Controller) *MockStatusInterface {
	mock := &MockStatusInterface{ctrl: ctrl}
	mock.recorder = &MockStatusInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusInterface) EXPECT() *MockStatusInterfaceMockRecorder {
	return m.recorder
}

// FindSnapshotWithOpenedPR mocks base method.
func (m *MockStatusInterface) FindSnapshotWithOpenedPR(arg0 context.Context, arg1 *[]v1alpha1.Snapshot, arg2 *v1alpha1.Snapshot) (*v1alpha1.Snapshot, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSnapshotWithOpenedPR", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.Snapshot)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindSnapshotWithOpenedPR indicates an expected call of FindSnapshotWithOpenedPR.
func (mr *MockStatusInterfaceMockRecorder) FindSnapshotWithOpenedPR(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSnapshotWithOpenedPR", reflect.TypeOf((*MockStatusInterface)(nil).FindSnapshotWithOpenedPR), arg0, arg1, arg2)
}

// GetReporter mocks base method.
func (m *MockStatusInterface) GetReporter(arg0 *v1alpha1.Snapshot) ReporterInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReporter", arg0)
	ret0, _ := ret[0].(ReporterInterface)
	return ret0
}

// GetReporter indicates an expected call of GetReporter.
func (mr *MockStatusInterfaceMockRecorder) GetReporter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReporter", reflect.TypeOf((*MockStatusInterface)(nil).GetReporter), arg0)
}

// IsMRInSnapshotOpened mocks base method.
func (m *MockStatusInterface) IsMRInSnapshotOpened(arg0 context.Context, arg1 ReporterInterface, arg2 *v1alpha1.Snapshot) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMRInSnapshotOpened", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsMRInSnapshotOpened indicates an expected call of IsMRInSnapshotOpened.
func (mr *MockStatusInterfaceMockRecorder) IsMRInSnapshotOpened(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMRInSnapshotOpened", reflect.TypeOf((*MockStatusInterface)(nil).IsMRInSnapshotOpened), arg0, arg1, arg2)
}

// IsPRInSnapshotOpened mocks base method.
func (m *MockStatusInterface) IsPRInSnapshotOpened(arg0 context.Context, arg1 ReporterInterface, arg2 *v1alpha1.Snapshot) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPRInSnapshotOpened", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsPRInSnapshotOpened indicates an expected call of IsPRInSnapshotOpened.
func (mr *MockStatusInterfaceMockRecorder) IsPRInSnapshotOpened(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPRInSnapshotOpened", reflect.TypeOf((*MockStatusInterface)(nil).IsPRInSnapshotOpened), arg0, arg1, arg2)
}

// IsPRMRInSnapshotOpened mocks base method.
func (m *MockStatusInterface) IsPRMRInSnapshotOpened(arg0 context.Context, arg1 *v1alpha1.Snapshot) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPRMRInSnapshotOpened", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsPRMRInSnapshotOpened indicates an expected call of IsPRMRInSnapshotOpened.
func (mr *MockStatusInterfaceMockRecorder) IsPRMRInSnapshotOpened(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPRMRInSnapshotOpened", reflect.TypeOf((*MockStatusInterface)(nil).IsPRMRInSnapshotOpened), arg0, arg1)
}
