name: AgentReady Assessment
on:
  pull_request:
    branches: [ main ]

jobs:
  agentready:
    name: Check repo with agentready
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.14'
      - uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318 # v1
        with:
          packages: |
            agentready==2.52.2

      - name: Run agentready check
        run: |
          agentready --version
          agentready assess --config "${GITHUB_WORKSPACE}"/.agentready/config/.agentready-config.yaml .
