name: Go Test on Pull Requests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  go:
    name: Check sources
    runs-on: ubuntu-20.04
    container: fedora:35
    env:
      OPERATOR_SDK_VERSION: v1.18.0
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download fedora environment dependencies # Would be nice to cache this somehow
        run: sudo dnf -y install diffutils findutils gcc wget which jq git
      - name: Cache Operator SDK ${{ env.OPERATOR_SDK_VERSION }}
        uses: actions/cache@v2
        id: cache-operator-sdk
        with:
          path: ~/cache
          key: operator-sdk-${{ env.OPERATOR_SDK_VERSION }}
      - name: Download Operator SDK ${{ env.OPERATOR_SDK_VERSION }}
        if: steps.cache-operator-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/cache
          wget https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk_linux_amd64 -O ~/cache/operator-sdk-${OPERATOR_SDK_VERSION} > /dev/null -O ~/cache/operator-sdk-${OPERATOR_SDK_VERSION} > /dev/null
          chmod +x ~/cache/operator-sdk-${OPERATOR_SDK_VERSION}
      - name: Install Operator SDK ${{ env.OPERATOR_SDK_VERSION }}
        run: |
          mkdir -p ~/bin
          cp ~/cache/operator-sdk-${OPERATOR_SDK_VERSION} ~/bin/operator-sdk
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Regenerate executables with current environment packages
        run: |
          rm -f bin/kustomize bin/controller-gen
          make kustomize controller-gen
      - name: Cache go modules
        id: cache-mod
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download dependencies
        run: go mod download
        if: steps.cache-mod.outputs.cache-hit != 'true'
      - name: Check go mod status
        run: |
          time_before=$(date "+%F %T")
          go mod tidy
          if [[ $(find . -type f -newermt "$time_before") ]]
          then
            echo "Go mod state is not clean:"
            find . -type f -newermt "$time_before"
            exit 1
          fi
      - name: Check format
        run: |
          time_before=$(date "+%F %T")
          make fmt
          if [[ $(find . -type f -newermt "$time_before") ]]
          then
            echo "Some files are not properly formatted."
            echo "Please run `go fmt` and amend your commit."
            find . -type f -newermt "$time_before"
            exit 1
          fi
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          install-go: false
      - name: Check manifests # make generate manifests touches files even for no changes
        run: |
          cp -rp ../integration-service/ /tmp/integration-service/
          make generate manifests
          if [[ $(diff -r ../integration-service /tmp/integration-service) ]]
          then
            echo "generated sources are not up to date:"
            diff -r ../integration-service /tmp/integration-service
            exit 1
          fi
      - name: Check kubernetes manifests
        run: |
          make generate manifests
          if [[ ! -z $(git status ':(exclude)bin/kustomize' ':(exclude)bin/controller-gen' -s) ]]
          then
            echo "generated sources are not up to date:"
            git --no-pager diff ':(exclude)bin/kustomize' ':(exclude)bin/controller-gen'
            exit 1
          fi
      - name: Check RBAC wildcards
        run: |
          if grep -rni "*" /tmp/integration-service/config/rbac/* ; then
            echo "generated RBAC roles contains wildcards"
            exit 1
          fi
      - name: Run Go Tests
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  docker:
    name: Check docker build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if dockerimage build is working
        run: docker build -f ./Dockerfile .

  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install gitlint into container
        run: python -m pip install gitlint
      - name: Run gitlint check
        run: gitlint --commits origin/${{ github.event.pull_request.base.ref }}..HEAD
